services:
  django:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 kaskad_project.wsgi:application"
    volumes:
      - .:/app
      - static_data:/app/static
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  static_data:
